"""add exercise

Revision ID: 1dea5a2000ba
Revises: fbc426a6b7d7
Create Date: 2022-09-04 15:40:12.085329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dea5a2000ba'
down_revision = 'fbc426a6b7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_category',
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('exercise',
    sa.Column('exercise_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('exercise_name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['exercise_category.category_id'], ),
    sa.PrimaryKeyConstraint('exercise_id'),
    sa.UniqueConstraint('exercise_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise')
    op.drop_table('exercise_category')
    # ### end Alembic commands ###
